# name: A workflow for my Hello World file
# on: push

# jobs:
#   startup:
#     name: Hello world action2
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: ./action-a
#         with:
#           MY_NAME: "Ahmed"
#   build:
#     name: Hello world action
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: ./action-a
#         with:
#           MY_NAME: "Osama"

name: 1.0$(Rev:.r)

# simplified trigger (implied branch)
trigger:

- main

# equivalents trigger
# trigger:
#  branches:
#    include:
#    - main

variables:
  name: martin

pool:
  vmImage: ubuntu-latest

jobs:

- job1: helloworld
  steps:

    - script: echo "Hello, $(name)"
